import nodemailer from 'nodemailer';

export async function sendEmailDigest(dealsByKeyword) {
  const { EMAIL_HOST, EMAIL_PORT, EMAIL_USER, EMAIL_PASS, EMAIL_TO } = process.env;
  if (!EMAIL_HOST || !EMAIL_USER || !EMAIL_PASS || !EMAIL_TO) return;

  const keywords = Object.keys(dealsByKeyword);
  if (!keywords.length) return;

  const totalDeals = keywords.reduce((sum, kw) => sum + dealsByKeyword[kw].length, 0);
  const date = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
  const subject = `FB Marketplace Deals — Belfast — ${date} (${totalDeals} deal${totalDeals !== 1 ? 's' : ''})`;

  const transporter = nodemailer.createTransport({
    host: EMAIL_HOST,
    port: parseInt(EMAIL_PORT ?? '587', 10),
    secure: EMAIL_PORT === '465',
    auth: { user: EMAIL_USER, pass: EMAIL_PASS },
  });

  // ── HTML ──────────────────────────────────────────────────────────────────
  const profitColor = (profit) => {
    const n = parseFloat(profit);
    if (n >= 100) return '#2e7d32';   // green
    if (n >= 50)  return '#e65100';   // amber
    return '#333';
  };

  const tableStyle = 'border-collapse:collapse;width:100%;font-size:13px;margin-bottom:24px;';
  const thStyle   = 'background:#1a1a2e;color:#fff;padding:8px 10px;text-align:left;white-space:nowrap;';
  const tdStyle   = 'padding:7px 10px;border-bottom:1px solid #e0e0e0;vertical-align:top;';
  const trAlt     = 'background:#f9f9f9;';

  let htmlSections = '';
  for (const keyword of keywords) {
    const deals = dealsByKeyword[keyword];
    const rows = deals.map((deal, i) => {
      const bg = i % 2 === 1 ? `style="${trAlt}"` : '';
      const profitStyle = `style="${tdStyle}color:${profitColor(deal.estimatedProfitGBP)};font-weight:600;"`;
      return `
        <tr ${bg}>
          <td style="${tdStyle}">${deal.matchedItem ?? '—'}</td>
          <td style="${tdStyle}">${deal.price}</td>
          <td style="${tdStyle}">£${deal.estimatedResaleGBP}</td>
          <td style="${tdStyle}">£${deal.netAfterFeesGBP}</td>
          <td ${profitStyle}>£${deal.estimatedProfitGBP}</td>
          <td style="${tdStyle}">${deal.roiPercent}%</td>
          <td style="${tdStyle}">${deal.condition ?? 'used'}</td>
          <td style="${tdStyle}"><a href="${deal.url}" style="color:#1565c0;">View</a></td>
        </tr>`;
    }).join('');

    htmlSections += `
      <h2 style="font-family:sans-serif;font-size:16px;color:#1a1a2e;margin:24px 0 8px;">${keyword}</h2>
      <table style="${tableStyle}">
        <thead>
          <tr>
            <th style="${thStyle}">Item</th>
            <th style="${thStyle}">Buy</th>
            <th style="${thStyle}">Resale</th>
            <th style="${thStyle}">Net</th>
            <th style="${thStyle}">Profit</th>
            <th style="${thStyle}">ROI%</th>
            <th style="${thStyle}">Condition</th>
            <th style="${thStyle}">Link</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>`;
  }

  const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:24px;background:#f4f4f4;font-family:sans-serif;">
  <div style="max-width:860px;margin:0 auto;background:#fff;border-radius:8px;padding:28px 32px;box-shadow:0 2px 8px rgba(0,0,0,.08);">
    <h1 style="font-size:20px;color:#1a1a2e;margin:0 0 4px;">FB Marketplace Deals — Belfast</h1>
    <p style="color:#666;font-size:13px;margin:0 0 20px;">${date} · ${totalDeals} deal${totalDeals !== 1 ? 's' : ''} found</p>
    ${htmlSections}
    <hr style="border:none;border-top:1px solid #e0e0e0;margin:24px 0 12px;">
    <p style="color:#aaa;font-size:11px;margin:0;">Generated by FB Marketplace Scraper</p>
  </div>
</body>
</html>`;

  // ── Plain text fallback ───────────────────────────────────────────────────
  let text = `FB Marketplace Deals — Belfast — ${date} (${totalDeals} deal${totalDeals !== 1 ? 's' : ''})\n\n`;
  for (const keyword of keywords) {
    text += `=== ${keyword} ===\n`;
    dealsByKeyword[keyword].forEach((deal, i) => {
      text += `\n  ${i + 1}. ${deal.matchedItem ?? deal.title}\n`;
      text += `     Buy: ${deal.price}  |  Resale: £${deal.estimatedResaleGBP}  |  Net: £${deal.netAfterFeesGBP}\n`;
      text += `     Profit: £${deal.estimatedProfitGBP}  |  ROI: ${deal.roiPercent}%  |  Condition: ${deal.condition ?? 'used'}\n`;
      text += `     ${deal.url}\n`;
    });
    text += '\n';
  }
  text += 'Generated by FB Marketplace Scraper\n';

  // ── Send ──────────────────────────────────────────────────────────────────
  try {
    await transporter.sendMail({
      from: EMAIL_USER,
      to: EMAIL_TO,
      subject,
      text,
      html,
    });
    console.log(`[email] Digest sent to ${EMAIL_TO} — "${subject}"`);
  } catch (err) {
    console.warn(`[email] Failed to send digest: ${err.message}`);
  }
}
